#!/usr/bin/env sh

source version.env

chmod +x ./gradlew

./gradlew build
./gradlew fatJar

rm -rf macos-package-dir

jpackage --type pkg \
 --temp macos-package-dir \
 --name TournamentApp \
 --input ./build/libs \
 --main-jar untitled-"$TOURNAMENT_VERSION"-standalone.jar\
 --main-class org.example.AppKt
