name: Test and build Gradle project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Makes `gradlew` executable
        run: chmod +x ./gradlew
                
      - name: Tests application
        run: ./gradlew test
        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Makes `gradlew` executable
        run: chmod +x ./gradlew

      - name: Builds application
        run: ./gradlew build
